# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '10.16'
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+/"
install:
- yarn
script:
- stty cols 80
- yarn test:cov
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: ci@terascope.io
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: terascope/fetch-github-release
