# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '12'
  - '14'
branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+/"
install:
  - yarn
before_script:
  - yarn build
script:
  - stty cols 80
  - yarn test
after_script:
  - yarn lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - yarn run clean
  - yarn run build
  - ls -la ./dist/
deploy:
  provider: npm
  email: ci@terascope.io
  api_token: $NPM_TOKEN
  cleanup: false
  on:
    tags: true
    repo: terascope/fetch-github-release
